version: '3'

services: 
    postgres-service:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
        healthcheck:
            test: "pg_isready -h localhost -p 5432 -q -U postgres"
            interval: 10s
            timeout: 10s
            retries: 5            
    redis:
        image: 'redis:latest'
     
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
        depends_on: 
            - api
            - client

    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        
        #command: ["./wait-for-postgres.sh", "postgres-service"]

        depends_on: 
            - postgres-service
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST:redis
            - REDIS_PORT:6379
            - PGUSER:postgres
            - PGHOST:postgres-service
            - PGDATABASE:postgres
            - PGPASSWORD:postgres_password
            - PGPORT:5432
          
    
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        stdin_open: true
        
    
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST:redis
            - REDIS_PORT:6379
